'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinXI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [de-DE] ;German
        '''MediaFound=&quot;Wird ausgeführt: Media Foundation-Wiedergabebewertung&quot;
        '''MediaExtend=&quot;Wird ausgeführt: Erweiterte Medienbewertung&quot;
        '''MediaEncode=&quot;Wird ausgeführt: Bewertung der Mediendecodierung/-codierung&quot;
        '''Memory=&quot;Wird ausgeführt: Bewertung der Systemspeiche&quot; ;Systemspeiche aus Kompatibilitätsgründen.
        '''Storage=&quot;Wird ausgeführt: Speicherbewertung&quot;
        '''
        '''[es-ES] ;Spanish
        '''MediaFound=&quot;En ejecución: Evaluación de reproducción de Media Foundation&quot;
        '''MediaExtend=&quot;En ejecución: Evaluación multimedia exten [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Compatibility() As String
            Get
                Return ResourceManager.GetString("Compatibility", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderGraphicDefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderGraphicDefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImgBusy24Px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImgBusy24Px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImgComplete24Px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImgComplete24Px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImgError32Px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImgError32Px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImgInfo32Px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImgInfo32Px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImgMainIcon24Px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImgMainIcon24Px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property imgMuerto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgMuerto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImgWarn32Px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImgWarn32Px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property segmdl2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("segmdl2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property segoeui() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("segoeui", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property segoeuib() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("segoeuib", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property seguisb() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("seguisb", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Settings]
        '''ShowHardwareOnStartup=false
        '''UseApiHardwareMode=false
        '''UseVerboseAssessmentMode=false
        '''ThemeColourInteger=0
        '''ApplyThemeColourToBorder=false
        '''UseCustomImgurApiKey=false
        '''CustomImgurApiKeyString=&quot;&quot;
        '''
        '''[Overrides]
        '''UpdateAutoCheck=false
        '''
        '''[States]
        '''StartState=0.
        '''</summary>
        Friend ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Windows6_1_KB2687862_x64() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Windows6_1_KB2687862_x64", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Windows6_1_KB2687862_x86() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Windows6_1_KB2687862_x86", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
